UPDATE "Asset" SET category = 'Router' WHERE category = 'RB 4011';
UPDATE "Asset" SET category = 'Managed PoE Switch' WHERE category = 'Tp-Link POE switch Manage';
UPDATE "Asset" SET category = 'Unmanaged PoE Switch' WHERE category = 'Tplink POE switch Unmanaged';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Tp-Link switch Omada';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Tp-Link switch 16 Port';
UPDATE "Asset" SET category = 'OLT' WHERE category = 'Tp-Link OLT';
UPDATE "Asset" SET category = 'Router' WHERE category = 'Mikrotik CCR 2004';
UPDATE "Asset" SET category = 'Router' WHERE category = 'Mikrotik CCR 1009';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Cisco switch 24 Port';
UPDATE "Asset" SET category = 'Dual Band Router' WHERE category = 'Tp-Link Router 1200 C6';
UPDATE "Asset" SET category = 'Dual Band Router' WHERE category = 'Tp-Link Router AX1500';
UPDATE "Asset" SET category = 'Dual Band Router' WHERE category = 'Tp-Link Router 1800';
UPDATE "Asset" SET category = 'ONU' WHERE category = 'Tp-Link ONU';
UPDATE "Asset" SET category = 'Access Point' WHERE category = 'Tp-Link AP 660 Omada';
UPDATE "Asset" SET category = 'Access Point' WHERE category = 'Tp-Link AP 670 Omada';
UPDATE "Asset" SET category = 'ONT' WHERE category = 'Tp-Link 1200 ONT';
UPDATE "Asset" SET category = 'ONT' WHERE category = 'Tp-Link 3000 ONT';
UPDATE "Asset" SET category = 'Access Point' WHERE category = 'Cisco AP C9115AXI-D';
UPDATE "Asset" SET category = 'Access Point' WHERE category = 'Cisco AP 3802I-D-K9';
UPDATE "Asset" SET category = 'Access Point' WHERE category = 'Ruckus 750/650';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Cisco Switch 8 Port';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Cisco Switch 24/28/48 Port';
UPDATE "Asset" SET category = 'SFP / Transceiver' WHERE category = 'SFP 1G/10G/Copper';
UPDATE "Asset" SET category = 'Telephone' WHERE category = 'Telephone';
UPDATE "Asset" SET category = 'VGA Splitter' WHERE category = 'VGA Splitter 2Port';
UPDATE "Asset" SET category = 'VGA Splitter' WHERE category = 'VGA Splitter 8Port';
UPDATE "Asset" SET category = 'Video Splitter' WHERE category = 'HDTV Splitter 2/4 Port';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Tplink Gigabit switch SG108E';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Tplink Switch 24 Port SG1024D';
UPDATE "Asset" SET category = 'Switch' WHERE category = 'Tplink Switch 16 Port SG1016D';
UPDATE "Asset" SET category = 'Network Cable Tester' WHERE category = 'Lan Tester';
UPDATE "Asset" SET category = 'UPS' WHERE category = 'Mini UPS';
UPDATE "Asset" SET category = 'PoE Injector' WHERE category = 'POE Injector';
UPDATE "Asset" SET category = 'Printer' WHERE category = 'Brother Printer';
UPDATE "Asset" SET category = 'Display / Monitor' WHERE category = 'LED LG/Zebster';
UPDATE "Asset" SET category = 'Fiber Equipment' WHERE category = 'Fiber Machine';
UPDATE "Asset" SET category = 'UPS' WHERE category = 'UPS';
UPDATE "Asset" SET category = 'ONT' WHERE category = 'Location ONT';
UPDATE "Asset" SET category = 'Laptop' WHERE category = 'Laptop';
UPDATE "Asset" SET category = 'Tool' WHERE category = 'Laser';
UPDATE "Asset" SET category = 'Power Supply' WHERE category = 'Dell Power supply';
UPDATE "Asset" SET category = 'Printer' WHERE category = 'Printer';
UPDATE "Asset" SET category = 'Mini PC' WHERE category = 'Mini PC';
UPDATE "Asset" SET category = 'Access Point' WHERE category = 'Cisco/HP/Unifi/Ruckus AP';
UPDATE "Asset" SET category = 'Server' WHERE category = 'Cisco server';
